-- Migration du nouveau workflow ACTIVITES CENTRE.
-- Le workflow concerne uniquement les centres Alpha : ID_ALPHA référence alpha(ID_CENTRE).

SET @col_exists := (
  SELECT COUNT(*)
  FROM information_schema.columns
  WHERE table_schema = DATABASE()
    AND table_name = 'visite'
    AND column_name = 'VALIDEE_COORDONNATEUR'
);
SET @ddl := IF(@col_exists = 0,
  'ALTER TABLE visite ADD COLUMN VALIDEE_COORDONNATEUR TINYINT(1) DEFAULT 0',
  'SELECT 1'
);
PREPARE stmt FROM @ddl;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

CREATE TABLE IF NOT EXISTS suivi_iepp (
  ID_SUIVI_IEPP INT NOT NULL AUTO_INCREMENT,
  ID_ALPHA INT NOT NULL,
  NOMBRE_VISITE_EFFECTUE_PAR_IEPP INT NULL,
  NOMBRE_REUNION_POINT_ACTIVITE_ALPHA INT NULL,
  VALIDEE_IEPP TINYINT(1) DEFAULT 0,
  PRIMARY KEY (ID_SUIVI_IEPP),
  INDEX IDX_SUIVI_IEPP_ALPHA (ID_ALPHA),
  CONSTRAINT FK_SUIVI_IEPP_ALPHA FOREIGN KEY (ID_ALPHA) REFERENCES alpha (ID_CENTRE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS suivi_superviseur (
  ID_SUIVI_SUPERVISEUR INT NOT NULL AUTO_INCREMENT,
  ID_ALPHA INT NOT NULL,
  NOMBRE_VISITE_SUPERVISEUR_EFFECTUE INT NULL,
  NOMBRE_REUNION_BILAN_SUPERVISEUR INT NULL,
  VALIDEE_SUPERVISEUR TINYINT(1) DEFAULT 0,
  PRIMARY KEY (ID_SUIVI_SUPERVISEUR),
  INDEX IDX_SUIVI_SUPERVISEUR_ALPHA (ID_ALPHA),
  CONSTRAINT FK_SUIVI_SUPERVISEUR_ALPHA FOREIGN KEY (ID_ALPHA) REFERENCES alpha (ID_CENTRE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
