-- Champs promoteur personne physique (formulaire centres) et métadonnées CEC.
-- Exécuter sur la base cible avant déploiement du backend mis à jour.

ALTER TABLE personnephysique
  ADD COLUMN SEXE VARCHAR(30) NULL,
  ADD COLUMN DATE_NAISSANCE DATE NULL,
  ADD COLUMN ANCIENNETE VARCHAR(100) NULL,
  ADD COLUMN BOITE_POSTALE VARCHAR(100) NULL,
  ADD COLUMN NIVEAU_ETUDES VARCHAR(150) NULL,
  ADD COLUMN CIVILITE VARCHAR(30) NULL;

ALTER TABLE cec
  ADD COLUMN ECOLE_TUTRICE VARCHAR(200) NULL,
  ADD COLUMN ANNEE_CREATION INT NULL;
