CREATE TABLE IF NOT EXISTS saisie_workflow (
  ID_SAISIE_WORKFLOW INT NOT NULL AUTO_INCREMENT,
  RESOURCE_PATH VARCHAR(180) NOT NULL,
  RECORD_ID INT NOT NULL,
  STATUT VARCHAR(40) NOT NULL DEFAULT 'BROUILLON',
  MOTIF_REJET VARCHAR(500) NULL,
  COMMENTAIRE_RETOUR VARCHAR(500) NULL,
  SOUMIS_PAR VARCHAR(100) NULL,
  PROPRIETAIRE VARCHAR(100) NULL,
  DECIDE_PAR VARCHAR(100) NULL,
  DATE_SOUMISSION DATETIME(6) NULL,
  DATE_DECISION DATETIME(6) NULL,
  PRIMARY KEY (ID_SAISIE_WORKFLOW),
  UNIQUE KEY uk_saisie_workflow_resource_record (RESOURCE_PATH, RECORD_ID)
);
